# Generated by Django 4.2.7 on 2026-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='anomaly_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='health_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='recommendations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='risk_level',
            field=models.CharField(max_length=20),
        ),
    ]
